### ISSUE TITLE
Initial draft of Problem Statement ready for review!

### ISSUE THREAD

**Issue by andreamclemeno** [andreamclemeno/CAS741-Diagnose#1]
Good Evening Dr. Smith!

The PDF and LaTex files for my initial draft of my Problem Statement are currently on my project repo: CAS741-Concentration-of-Virus. Please review them! At the end of this issue, you can find the links on the corresponding paths. 

I changed my project idea since we last spoke. I hope it can still fit in with the Drasil option. I tried to find a good medium between my two ideas! For reference, the differential equation I want to investigate can be seen below:
![image](https://user-images.githubusercontent.com/70977402/93838916-3e8df100-fc59-11ea-964a-d9c4565b2e70.png)
where P is an unknown function representing the rate of virus production, c is a constant called the clearance rate constant, and V is the virus concentration.

It is a very simple dynamic model of HIV concentration. I found it in the introduction of this [research article](https://www.hindawi.com/journals/ddns/2008/903678/).

I hope everything was done correctly! It is my first time using LaTex! 

Thanks in advance for your feedback!

PDF: [docs/ProblemStatement/ProblemStatement.pdf](https://github.com/andreamclemeno/CAS741-Concentration-of-Virus/blob/master/docs/ProblemStatement/ProblemStatement.pdf)
LaTex: [docs/ProblemStatement/ProblemStatement.tex](https://github.com/andreamclemeno/CAS741-Concentration-of-Virus/blob/master/docs/ProblemStatement/ProblemStatement.tex)

**Comment by smiths** [comment]
Good start @andreamclemeno.  

I have the following feedback on your problem statement:

- Split the last paragraph into two, at the point of "This project will ..."
- You should mention that your project will be based on Drasil (this request deviates from the requirement to be abstract, but it is an important constraint on your project) - once we are comfortable with your draft SRS, you will want to fork the Drasil repo and move your development there
- normally I don't like equations in a problem statement, but I think including your ODE makes sense for your problem statement (it clarifies what you are solving for).
- you removed the ability for me to make comments in your tex file, please follow the blank project template to add this capability back to this file (and to future files)
- please set your text editor to hard wrap at 80 characters (this will make future diffs easier to see)
- include the `.gitignore` file from the blank project template

Once you address the above concerns, I will approve your problem statement (and close this issue).

**Comment by andreamclemeno** [comment]
Thanks @smiths ! Hopefully the new versions of the files will address the concerns you mentioned. Let me know if I should add or change anything else!

**Comment by smiths** [comment]
Thank you @andreamclemeno.  We are getting closer, but I still have some changes to request.  :smile:

- the `.gitignore` file is a hidden file.  The name has to be exactly as shown.  You can learn more about hidden files at https://en.wikipedia.org/wiki/Hidden_file_and_hidden_directory
- you don't need the conditions around the comments, since comments are turned on or off in the `.Comments.tex` file
- a separate section for Comments is not necessary.  Since there aren't actually any comments, you can delete this section, and all of its contents

The problem statement itself is great.  I'll "officially" approve it now.  :smile:.  We'll close this issue once you've had a chance to address the above points.

**Comment by andreamclemeno** [comment]
@smiths 

Hi Dr. Smith!!

I completed these changes. Thanks for your feedback! 

One thing that may be wrong is how I did my .gitignore files. If you could check if this is [one](https://github.com/andreamclemeno/CAS741-Concentration-of-Virus/blob/master/.gitignore) is created in the right way, then the other [one](https://github.com/andreamclemeno/CAS741-Concentration-of-Virus/blob/master/docs/.gitignore) should be good too! Just let me know and I can fix them!! Thanks!

**Comment by smiths** [comment]
The `.gitignore` files look fine.

You are still missing `Comments.tex` file.  I've added it in commit d729a44.
