### ISSUE TITLE
VnVPlan: Minor distinction on page 12

### ISSUE THREAD

**Issue by liziscool** [andreamclemeno/CAS741-Diagnose#11]
Hi @andreamclemeno ,

On page 12 of the VnV Plan, it says that X is a percentage, but the equation above defines X as fraction whose maximum is 1, I think? I think you might need to add the (x100) part to the equation.

Found here: https://github.com/andreamclemeno/CAS741-Concentration-of-Virus/blob/master/docs/VnVPlan/BlankProjectTemplate_docs_VnVPlan_VnVPlan.pdf

**Comment by andreamclemeno** [comment]
Hi @liziscool ! 

Yeah I did. I ended up taking it out and not putting it as a test! Thanks for catching it 

Andrea
