### ISSUE TITLE
VnVPlan: Section 5.2.2 Reliability Test Cases

### ISSUE THREAD

**Issue by liziscool** [andreamclemeno/CAS741-Diagnose#12]
Hi @andreamclemeno,

I have a question about the test cases in section 5.2.2, I understand you are comparing the output of your program to subject profiles from an academic journal. I was just wondering how many 'profiles' you are using. I think it would be useful to include a table of all these cases (i.e. inputs, expected output, experimental output - left blank for now) if it is manageable. If there are way too many test cases then maybe a portion of the test cases in a table would be sufficient.

**Comment by andreamclemeno** [comment]
Yeah that sounds good Liz!! I am going to add a table for them in my VnV report and then I will update this issue!

**Comment by andreamclemeno** [comment]
Done! thanks I added it in here

added in: d8c646e8a3ed2a3ed0b5240028371225174aaebf
