### ISSUE TITLE
SRS doesn't compile

### ISSUE THREAD

**Issue by smiths** [andreamclemeno/CAS741-Diagnose#13]
@andreamclemeno your SRS does not compile on my machine.  It looks like your `Comments_new.tex` file is not under version control.  (You shouldn't really need a new Comments file, you can just modify the existing Comments file.)

When I fixed the first problem, there were additional problems with compiling the equations.  There is a problem with many of the equations.

**Comment by andreamclemeno** [comment]
Hi @smiths 

I think I fixed this issue as I have no errors when running it when I cloned my repo on my virtual machine. It can be found here: ee082999826e869d5035d7342af9eb52f77f2f4c

Thanks!!

Andrea

**Comment by smiths** [comment]
@andreamclemeno, yes, I can verify that your SRS now compiles.

My first thought when I saw this issue was that you were talking about the Drasil generator, since your Drasil generator fails on make, because stable doesn't match build.  I know this isn't related to the current issue, but because it might help you - for the Drasil version you should copy the contents of your build into the stable folder (once you are convinced that build is correct).  You'll need to then put the new stable under version control so that others will also succeed with make.

**Comment by andreamclemeno** [comment]
@smiths Thanks for checking Dr. Smith! 

Also, I will check it out the build and stable folders today to fix it! Thank you☺️
