### ISSUE TITLE
Tables of symbols repeats information

### ISSUE THREAD

**Issue by JohnErnsthausen** [andreamclemeno/CAS741-Diagnose#14]
The tables of symbols repeats information which should be maintained in the SRS document. Repeating information makes document maintenance hard.

See comment in template
[symbols, abbreviations or acronyms – you can simply reference the SRS
(Author, 2019) tables, if appropriate —SS]

**Comment by andreamclemeno** [comment]
Okok got it! Thanks!!

![image](https://user-images.githubusercontent.com/70977402/102001293-658b1a80-3cbe-11eb-8c76-2950fbf353ac.png)


commit: 7ab3d11eafab2123d04d516dff733eb9c5128131
