### ISSUE TITLE
Program name

### ISSUE THREAD

**Issue by JohnErnsthausen** [andreamclemeno/CAS741-Diagnose#15]
Table 2 says the software name is diagnosis-AIDS. However in the text of the document such as the last paragraph of Section 2 the software is called diagnosisAIDs (with little s and no hyphen). This happens several times in the VnVPlan document. In Section 3.1, AIDS is denoted AIDs (with little s). Is this intentional?

**Comment by andreamclemeno** [comment]
Changed it all to \progname{}

commit: 7ab3d11
