### ISSUE TITLE
Verification and validation are methods

### ISSUE THREAD

**Issue by JohnErnsthausen** [andreamclemeno/CAS741-Diagnose#16]
Section 4.1 starts out "Verification and validation are methods...". I'd say they are actions, as in actions done to code for example.

**Comment by andreamclemeno** [comment]
Thanks John!! I see what you mean

![image](https://user-images.githubusercontent.com/70977402/102001239-a46ca080-3cbd-11eb-9ac1-ecd5f14275df.png)

in commit: 7ab3d11eafab2123d04d516dff733eb9c5128131
