### ISSUE TITLE
Testing input

### ISSUE THREAD

**Issue by JohnErnsthausen** [andreamclemeno/CAS741-Diagnose#17]
Your input tests test for characters and numbers in section 5.1.1. If you are accepting user input into a string, things can get much more wild! %^*#, spaces, any combination of digits and these characters. I'd recommend insisting on only numbers, if this is what you ultimately want, by having the software reject any other characters.

**Comment by andreamclemeno** [comment]
Got it! I think I was confused writing the Vnv but I changed inputs to numbers in: 513057ea605a8816f37c57b4a6a80dfd18a4a09b

Thanks for your issue @JohnErnsthausen !!
