### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by JohnErnsthausen** [andreamclemeno/CAS741-Diagnose#18]
I read the VnVPlan document for diagnosis-AIDS. Is the software about a database, a computation, scalability, or something else? What is the computation that will require performance?

**Comment by andreamclemeno** [comment]
Hi @JohnErnsthausen !

There is a computation, an equation that I am using. I know that wasn't really clear with my previous VnV version.  The computation is: 

![image](https://user-images.githubusercontent.com/70977402/102132245-5bcdf800-3e21-11eb-8499-2b120b2f61a0.png)
![image](https://user-images.githubusercontent.com/70977402/102132322-786a3000-3e21-11eb-9d88-440d95168c96.png)

I am not sure if performance is what I meant. I changed it to be software reliability where I mean performance in terms of time like it will perform the computation at an efficient speed. I am not sure if this is what you mean but hopefully this answers your question! 

Thanks for your issues!

Andrea

**Comment by JohnErnsthausen** [comment]
Hello, @andreamclemeno.

I understand your statement now. Thank you. A modern laptop will have no trouble scaling this computation into the millions of users. Performance (perhaps meaning scalability) might degrade slightly if there is a database involved. In either case, I expect there will be no problems with performance due to computing exponentials and logarithms.

John
