### ISSUE TITLE
VnVPlan tex files

### ISSUE THREAD

**Issue by smiths** [andreamclemeno/CAS741-Diagnose#19]
The tex file (and pdf file) for the VnVPlan should be renamed to just be VnVPlan.tex (and VnVPlan.pdf).  Also, the tex files do not currently compile.  (A few typos were corrected in 6195919.)

**Comment by andreamclemeno** [comment]
Hi @smiths !

I changed their names. Should I delete the other ones? I was wondering for my SRS too as I saved those as the BlankTemplate_... too. I guess they're not necessary but to show the second drafts.

Also, I tried on my VM and the .tex files compile correctly on there when I clone the repo but I noticed progname is not working when I open the .dvi folder in Linux but on my Windows OS, the correct program name shows. I am not sure if this is a problem with my .tex file. I referenced common like this:

\input{../Comments}
\input{../Common}

Thanks!!

Andrea

**Comment by smiths** [comment]
@andreamclemeno, for future reference, you should use `git mv` when you are renaming files.  You can then change the name of the file and leave the contents the same.  The original file is still under version control, and someone could look for the old filename in older commits.

Since you didn't use `git mv`, you should just delete the previous files.  They will still be present under version control, but they won't show up for the latest version of the repo.

You also have two versions of `VnVPlan.pdf` and `VnVPlan.tex`.  One where it should be, and another in the top of the folder structure.  Please delete the extra copy.

I can compile your `VnVPlan.tex` file, except the `progname` is `ProgName`.  You need to go into the `Comments.tex` file and change the `newcommand` to use your program's name.

**Comment by andreamclemeno** [comment]
@smiths Oh ok ok! Thanks for your help Dr. Smith! I have deleted the files, updated the Commons.tex in my repo and tested it on my VM. I just updated it with commit: e6cc4ea0bb8c10ed2034e7d0aa91bcc484e7fdf4
