### ISSUE TITLE
Drasil Generated SRS ready for review!

### ISSUE THREAD

**Issue by andreamclemeno** [andreamclemeno/CAS741-Diagnose#21]
Good evening Liz!!

The pdf of the .html is found on my project repo: https://github.com/andreamclemeno/CAS741-Concentration-of-Virus/blob/master/docs/SRS/Software%20Requirements%20Specification%20for%20Diagnose%20(1).pdf

The repo that this generated from is: https://github.com/andreamclemeno/Drasil

My code can be found: https://github.com/andreamclemeno/Drasil/tree/master/code/drasil-example/Drasil/Diagnose

Please make issues so I can improve my project!!

Thank you :)

Andrea

@liziscool

**Comment by liziscool** [comment]
Hi Andrea,
I briefly looked over this but I am a little confused about what I am supposed to review specifically. I think I am too unfamiliar with the Drasil framework. Should I look at your code? Or at some specific documents in your Drasil repo? Please let me know :)

**Comment by smiths** [comment]
@liziscool, you should look at the generated SRS - the first link that @andreamclemeno listed.

**Comment by andreamclemeno** [comment]
@liziscool Hi Liz! I added the pdf version of the generated SRS in the first link. Thanks ☺️

**Comment by andreamclemeno** [comment]
@liziscool Hi Liz! Dr. Smith is right! I added the pdf version of the generated SRS in the first link ! Thanks ☺️
