### ISSUE TITLE
Drasil Generate SRS ready for review!

### ISSUE THREAD

**Issue by andreamclemeno** [andreamclemeno/CAS741-Diagnose#22]
Good evening Salah!

The pdf of the .html is found on my project repo: https://github.com/andreamclemeno/CAS741-Diagnose/blob/master/docs/SRS/Software%20Requirements%20Specification%20for%20Diagnose.pdf

The repo that this generated from is: https://github.com/andreamclemeno/Drasil

My code can be found: https://github.com/andreamclemeno/Drasil/tree/master/code/drasil-example/Drasil/Diagnose

Please make issues so I can improve my project!!

Thank you :)

Andrea

@salahga

**Comment by andreamclemeno** [comment]
@salahhessien Sorry about that! Hopefully you this one is correct!

**Comment by salahhessien** [comment]
Hi @andreamclemeno,

I have done reviewing your SRS revision d5870d0, kindly address my opened ticket as appropriate.

Thanks,
Salah

**Comment by andreamclemeno** [comment]
Thanks @salahhessien ! I am looking at them now!
