### ISSUE TITLE
Does 'copies' belong in the SI table in the SRS document?

### ISSUE THREAD

**Issue by liziscool** [andreamclemeno/CAS741-Diagnose#23]
Hi @andreamclemeno,
I feel like the unit 'copies' doesn't fit in with the other entries of the SI table, perhaps it can be moved below the table as an 'additional unit'.
Found here https://github.com/andreamclemeno/CAS741-Concentration-of-Virus/blob/master/docs/SRS/Software%20Requirements%20Specification%20for%20Diagnose%20(1).pdf

**Comment by andreamclemeno** [comment]
Hi Liz,

Thanks for your feedback. I changed it to moles!

https://github.com/andreamclemeno/CAS741-Diagnose/blob/master/docs/SRS/Software%20Requirements%20Specification%20for%20Diagnose.pdf
