### ISSUE TITLE
Assumption allProductive is a little unclear to me?

### ISSUE THREAD

**Issue by liziscool** [andreamclemeno/CAS741-Diagnose#24]
Hi @andreamclemeno,

I am just wondering about assumption allProductive in the SRS. First, I think there may be a typo, but if my interpretation is correct then I am just confused as to if it is necessary to state? Or maybe it is just a misunderstanding due to my lack of background in the field. If it is the latter maybe you can add 'Productivity' to your terminology and description.

**Comment by andreamclemeno** [comment]
Hi @liziscool 

I added a better description of it in my updated traditional SRS here:
ee082999826e869d5035d7342af9eb52f77f2f4c 

I will add it to my Drasil code, put the commit and close this issue soon!

Thanks!!

Andrea

**Comment by andreamclemeno** [comment]
Hi @liziscool !

You're right it did sound a little confusing. This is what I changed it to:

![image](https://user-images.githubusercontent.com/70977402/101667766-baf4cc80-3a1d-11eb-90fb-131fe271b24a.png)
![image](https://user-images.githubusercontent.com/70977402/101667796-c47e3480-3a1d-11eb-88e5-61de065b71c4.png)

Hopefully this is more clear!! Thanks ! 

Andrea

**Comment by andreamclemeno** [comment]
Added in Drasil generated SRS: ee082999826e869d5035d7342af9eb52f77f2f4c
Added in traditional SRS: 137638a0353f847be4196d10e81f23989a3d504e
