### ISSUE TITLE
Question related to R3 in your SRS

### ISSUE THREAD

**Issue by salahhessien** [andreamclemeno/CAS741-Diagnose#25]
Hi @andreamclemeno,

**"chosen prediction period"** sentence in R3 below is not clear for me. When I checked the equation in IM1, the only parameter that I found it related to this statement is "t_t". Is this parameter the one used to set the prediction period?

R3: Calculate-Values: Software calculates the elimination rate of HIV and
the viral load at the chosen prediction period from IM1 and IM2.

![srs_r1](https://user-images.githubusercontent.com/60824110/101596506-31b0ac00-39c3-11eb-9e4b-ec8abe49c05d.PNG)

Thanks,
Salah

**Comment by andreamclemeno** [comment]
Hi @salahhessien 

I see what you mean! I updated it in this commit: ee082999826e869d5035d7342af9eb52f77f2f4c 

![image](https://user-images.githubusercontent.com/70977402/101666355-1b830a00-3a1c-11eb-8937-90559d0b7ca4.png)

Thanks!!

Andrea
