### ISSUE TITLE
missing reference in R5

### ISSUE THREAD

**Issue by salahhessien** [andreamclemeno/CAS741-Diagnose#26]
Hi @andreamclemeno,

I wonder if you can add a reference to the elimination rate and predicted virtual load in your R5 below. I believe you should cross reference to one or more GS here.

![srs_r2](https://user-images.githubusercontent.com/60824110/101597249-7557e580-39c4-11eb-8bca-848426aa273b.PNG)

Thanks,
Salah

**Comment by andreamclemeno** [comment]
Hi @salahhessien !

I think thats a good idea: 

![image](https://user-images.githubusercontent.com/70977402/101666470-3fdee680-3a1c-11eb-980b-0eab04db7d5b.png)

same commit as before: ee082999826e869d5035d7342af9eb52f77f2f4c

Thanks!!

Andrea
