### ISSUE TITLE
question related to NR4 (Maintainability) 

### ISSUE THREAD

**Issue by salahhessien** [andreamclemeno/CAS741-Diagnose#27]
Hi @andreamclemeno,

In NR4, you mentioned that you going to measure traceability by ensuring relationship from inputs to instance model is recorded. I believe you should also make sure the traceability is achieved a cross all other documents such as (VnV, MIS, MIG, etc.). Am I right?

![srs_r3](https://user-images.githubusercontent.com/60824110/101598334-ff547e00-39c5-11eb-85aa-266c2db7afd0.PNG)

Thanks,
Salah

**Comment by andreamclemeno** [comment]
Hi @salahhessien !

![image](https://user-images.githubusercontent.com/70977402/101666622-7157b200-3a1c-11eb-80d1-a530e3b5d8b7.png)

same commit as before: ee08299

Thanks!!

Andrea
