### ISSUE TITLE
Missing Drasil source code

### ISSUE THREAD

**Issue by salahhessien** [andreamclemeno/CAS741-Diagnose#28]
Hi @andreamclemeno,

Could you point me to your Drasil code?, I want to review it as well. I checked the "src" folder and it was empty

Thanks,
Salah

**Comment by andreamclemeno** [comment]
Hi @salahhessien !
This is where my Drasil code is. I should've put a link from my src file but it can be found in the issue.

The repo that this generated from is: https://github.com/andreamclemeno/Drasil

My code can be found: https://github.com/andreamclemeno/Drasil/tree/master/code/drasil-example/Drasil/Diagnose

Thanks!!
