### ISSUE TITLE
Question related to NR3 

### ISSUE THREAD

**Issue by salahhessien** [andreamclemeno/CAS741-Diagnose#29]
Hi @andreamclemeno,

I wonder how you going to achieve NR3 "Reusability", Is this something for granted by using Drasil? Or Do you need to follow a certain design rules to achieve that?

![srs_r4](https://user-images.githubusercontent.com/60824110/101600895-f2d22480-39c9-11eb-9304-c73258076ffe.PNG)

Thanks,
Salah

**Comment by andreamclemeno** [comment]
Hi @salahhessien !

Drasil has libraries of knowledge like physics or math knowledge that is already in the Drasil codes. So like I wouldn't need to code in information for moles for example. I would just need to reference the code already implemented in Drasil!

What do you think I should make it more clear?? or like maybe explain it more! 

Thanks!!

Andrea

**Comment by salahhessien** [comment]
Thanks @andreamclemeno for your comment, it is clear for me now. So you rely on the math and physics libraries that should be written in a modular and optimized way in Drasil I believe.

This ticket was just a question for me, and it is completely up to you to add one sentence mentioning what you explained to me if you feel this would be beneficial.

Best,
Salah
