### ISSUE TITLE
Table formatting in section 1.2 and 1.3 for SRS

### ISSUE THREAD

**Issue by liziscool** [andreamclemeno/CAS741-Diagnose#3]
Hi Andrea,

Just a minor thing, I think the tables in section 1.2 and 1.3 for you SRS should fall under their respective sections. So you should move table 2 before section 1.3 and table 3 before section 2 starts.

found here on page ii and iii: https://github.com/andreamclemeno/CAS741-Concentration-of-Virus/blob/master/docs/SRS/741_ViralLoad_docs_SRS_SRS.pdf

@andreamclemeno 
@smiths

**Comment by andreamclemeno** [comment]
Hi Liz!! 

Thank so much for your issues. I have been very busy lately but I will update my SRS and review these issues tonight! Thanks for your feedback.

Andrea

**Comment by andreamclemeno** [comment]
Hi Liz! I did the quick fix! Thanks!
