### ISSUE TITLE
4.1.2 Physical System Description should illustrate the 'whole' system

### ISSUE THREAD

**Issue by liziscool** [andreamclemeno/CAS741-Diagnose#4]
I am not too sure about this, but I think section 4.1.2 Physical System Description should pertain to the whole system, which in this case would be the whole human body, right? Is there a way you can represent the 'percentage' or 'concentration' of infected cells in the entire body? To me, that would align more with what the 'system' is in the problem you are trying to solve. 

Found here on page 6: https://github.com/andreamclemeno/CAS741-Concentration-of-Virus/blob/master/docs/SRS/741_ViralLoad_docs_SRS_SRS.pdf

**Comment by andreamclemeno** [comment]
Hi Liz. I am not sure of a way to show the concentration in the entire body but I do think that showing that it is within the body is a good detail to add. I added this image:
![physicalsys](https://user-images.githubusercontent.com/70977402/97110196-3a1c8400-16ae-11eb-972e-650876e9dd9f.JPG)

It is also on the new draft but I thought it would be easier to put it here.

**Comment by smiths** [comment]
Since @andreamclemeno addressed the issue, I will close it.
