### ISSUE TITLE
Assumptions A7, A9 are missing references, A8 should be referenced again for SRS section 4.2.1

### ISSUE THREAD

**Issue by liziscool** [andreamclemeno/CAS741-Diagnose#5]
Some of the assumptions are missing references in section 4.2.1, but they are definitely good assumptions so I imagine they must be used somewhere. Specifically, I think A7 and A8, pertaining to 'clearance rate', should be referenced by the IM where you calculate clearance rate, and A9 should be referenced by the IM that calculates the decay rate. 

However, it is unclear which IM the clearance rate is calculated in. It might be IM1, but it is a little confusing because IM1 says it uses lambda to find VL30, but lambda is listed as an output. I think this might stem from the fact that 'clearance rate' is used interchangeably with 'decay rate', and I am not too familiar with this field so that might be more clear to other readers. 

Found here on page 7 and 11: https://github.com/andreamclemeno/CAS741-Concentration-of-Virus/blob/master/docs/SRS/741_ViralLoad_docs_SRS_SRS.pdf

@andreamclemeno 
@smiths

**Comment by smiths** [comment]
Looks like a good issue @liziscool.  @andreamclemeno, if you make changes to your SRS to address this issue, please include the commit hash (or hashes) where the changes are made in the text of your issue closing comment.

**Comment by andreamclemeno** [comment]
Hi @liziscool !

Thanks for your input. I addressed these comments in 06d94d73922ad53588aeeff0bf87444eca09258b !
