### ISSUE TITLE
Where is the input variable "Age" used? SRS 4.2.6 Input data constraints

### ISSUE THREAD

**Issue by liziscool** [andreamclemeno/CAS741-Diagnose#6]
Hi Andrea,

'Age' is listed as an input variable in SRS 4.2.6 Input data constraints, but it is not used by any of the instance models. I am just wondering how it factors into your calculation, perhaps there is another instance model that is missing that could use it. 

If so, should Age also be represented in table 2 on page 1? With its unit being years?

found here on page 13: https://github.com/andreamclemeno/CAS741-Concentration-of-Virus/blob/master/docs/SRS/741_ViralLoad_docs_SRS_SRS.pdf

@andreamclemeno 
@smiths

**Comment by andreamclemeno** [comment]
Hi Liz! 

I had another instance model to predict the progression of AIDs and I must have forgotten to take out everything about age and concepts related to that IM. I took out the age/patient information. I will continually look for other things too!! 

Thanks for bringing this up!

Andrea

**Comment by smiths** [comment]
@andreamclemeno, in the future when you close an issue, please include in your closing comment the commit hash that addresses the issue.  This helps with traceability.
