### ISSUE TITLE
Initial draft of VnV plan ready for review!

### ISSUE THREAD

**Issue by andreamclemeno** [andreamclemeno/CAS741-Diagnose#7]
Hi Dr. Smith ! 

The PDF and LaTex files for my initial draft of my VnV Plan are currently on my project repo: CAS741-Concentration-of-Virus. Please review them! At the end of this issue, you can find the links on the corresponding paths.

[docs/VnVPlan/BlankProjectTemplate_docs_VnVPlan_VnVPlan.pdf](https://github.com/andreamclemeno/CAS741-Concentration-of-Virus/blob/master/docs/VnVPlan/BlankProjectTemplate_docs_VnVPlan_VnVPlan.pdf)
[docs/VnVPlan/BlankProjectTemplate_docs_VnVPlan_VnVPlan.tex](https://github.com/andreamclemeno/CAS741-Concentration-of-Virus/blob/master/docs/VnVPlan/BlankProjectTemplate_docs_VnVPlan_VnVPlan.tex)

Thank you :)

Andrea

@smiths

**Comment by smiths** [comment]
Comments on the VnV plan are given in 6195919 and in #19.
